# Generated by Django 2.2.5 on 2021-01-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_time', models.DateTimeField(verbose_name='Received Time')),
                ('mail_subject', models.CharField(max_length=64, verbose_name='Subject')),
                ('sender', models.CharField(max_length=32, verbose_name='Sender')),
                ('sender_email_address', models.EmailField(max_length=254, verbose_name='Sender Email Address')),
                ('url_list', models.CharField(max_length=1024, verbose_name='Zoom URL List')),
                ('url_numbers', models.IntegerField(verbose_name='Numbers of URLs')),
            ],
        ),
    ]
