# Generated by Django 2.2.5 on 2021-01-05 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping_tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledZoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Event Name')),
                ('scheduled_datetime', models.DateTimeField(verbose_name='Scheduled Date and Time')),
                ('comment', models.TextField(max_length=256, null=True, verbose_name='Comment')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='scraping_tool.Mail', verbose_name='Mail')),
            ],
        ),
    ]
