# Generated by Django 3.1.5 on 2021-01-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping_tool', '0004_remove_mail_mail_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='body',
            field=models.TextField(max_length=2048, null=True, verbose_name='Body'),
        ),
    ]
